[package]
name = "os"
version = "0.1.0"
authors = ["James Blizzard <jim@acidhl.co.uk>"]

[lib]
crate-type = ["staticlib"]

[profile.release]
panic = "abort"

[dependencies]
bit_field = "0.5.0"
bitflags = "0.7.0"
multiboot2 = "0.1.0"
once = "0.3.2"
rlibc = "0.1.4"
spin = "0.3.4"
volatile = "0.1.0"

[dependencies.hole_list_allocator]
path = "libs/hole_list_allocator"

[dependencies.lazy_static]
features = ["spin_no_std"]
version = "0.2.1"

[dependencies.x86]
default-features = false
version = "0.7.1"

[workspace]